/**
 * This is header file for native C++ library.
 * It contains function declarations for all the native functions defined in native library.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_asu_msrs_artcelerationlibrary_NativeClass */

#ifndef _Included_edu_asu_msrs_artcelerationlibrary_NativeClass
#define _Included_edu_asu_msrs_artcelerationlibrary_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_asu_msrs_artcelerationlibrary_NativeClass
 * Method:    getMessageFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_asu_msrs_artcelerationlibrary_NativeClass_getMessageFromJNI
  (JNIEnv *, jclass);
JNIEXPORT jobject JNICALL Java_edu_asu_msrs_artcelerationlibrary_NativeClass_rotateBitmapCcw90
        (JNIEnv * , jobject , jobject );
JNIEXPORT jobject JNICALL Java_edu_asu_msrs_artcelerationlibrary_NativeClass_colorfilterndk(JNIEnv * , jobject  , jobject , jintArray );
JNIEXPORT jobject JNICALL Java_edu_asu_msrs_artcelerationlibrary_NativeClass_motionblurneon(JNIEnv * , jobject  , jobject , jint , jint );


#ifdef __cplusplus
}
#endif
#endif
